services:
  redis:
    image: redis
    cpu_count: 1
    mem_limit: 1G
    restart: unless-stopped
    ports:
      - 6379:6379
  crayonccp:
    image: crayonccp
    build:
      context: .
      dockerfile: CrayonCCP/Dockerfile
    environment:
      ConnectionStrings__CrayonDbConnectionString: "<replace-this>",
      Security__Jwt__Secret: "<replace-this>",
      Security__Jwt__Issuer: "http://localhost:5221",
      Security__Jwt__Audience: "http://localhost:5221",
      Security__InitialUserDetails__Username: "Admin",
      Security__InitialUserDetails__Email: "<replace-this>",
      Security__InitialUserDetails__Password: "<replace-this>",
      Security__CCP__ClientId: "<replace-this>",
      Security__CCP__ClientSecret: "<replace-this>",
      Security__CCP__Endpoint: "<replace-this>"
  crayonapi:
    image: crayon.api
    build:
      context: .
      dockerfile: Crayon.API/Dockerfile
    environment:
      ConnectionStrings__CCPDbConnectionString: "<replace-this>"
      CCPRedisConnectionString: "<replace-this>"
      InitialClients__Crayon__Id: "00000000-0000-0000-0000-000000000001"
      InitialClients__Crayon__Name: "Crayon API"
      InitialClients__Crayon__Secret: "<replace-this>"