services:
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - crayon_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest  # SQL Server 2019
    container_name: sqldb
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "CHANGEME"  # Make sure to use a strong password
      MSSQL_PID: "Developer"
    ports:
      - "1443:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - crayon_net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
  crayonccp:
    image: crayonccp
    build:
      context: .
      dockerfile: CrayonCCP/Dockerfile
    environment:
      - "ASPNETCORE_URLS=http://+:5121"
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "CCPRedisConnectionString=<configured-later>"
      - "InitialClients__Crayon__Name=Crayon API"
    ports:
      - "5121:5121"
    networks:
      - crayon_net
    depends_on:
      - redis
      - sqldb
      - crayonapi
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
  crayonapi:
    image: crayon.api
    build:
      context: .
      dockerfile: Crayon.API/Dockerfile
    environment:
      - "ASPNETCORE_URLS=http://+:5221"
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "Security__CCP__Endpoint=http://localhost:5121"
    ports:
      - "5221:5221"
    networks:
      - crayon_net
    depends_on:
      - sqldb
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G

volumes:
  sql_data:  # Named volume for SQL Server persistent storage

networks:
  crayon_net:  # Custom network for the services